import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "medaxis-language";
const textDecoder = typeof TextDecoder !== "undefined" ? new TextDecoder("utf-8") : null;

const translations = {
  en: {
    "language.label": "Language",
    "language.english": "English",
    "language.hindi": "Hindi",
    "brand.tagline": "Care operations and admin control center",
    "brand.panel": "{role} panel",
    "brand.signedInAs": "Signed in as",
    "brand.logout": "Logout",
    "brand.userFallback": "Hospital Admin",
    "nav.dashboard": "Dashboard",
    "nav.patients": "Patients",
    "nav.doctors": "Doctors",
    "nav.appointments": "Appointments",
    "nav.billing": "Billing",
    "nav.departments": "Departments",
    "nav.staff": "Receptionist",
    "role.admin": "Admin",
    "role.doctor": "Doctor",
    "role.patient": "Patient",
    "role.staff": "Receptionist",
    "auth.network": "City Care Network",
    "auth.heroTitle": "Hospital operations, patient care, and billing in one calm workspace.",
    "auth.heroDescription": "Designed for administrators, clinicians, staff, and patients with role-aware access and connected records.",
    "auth.operations": "Operations",
    "auth.operationsDescription": "Appointments, patients, departments, and staffing aligned.",
    "auth.financials": "Financials",
    "auth.financialsDescription": "Billing visibility with live records and role-based workflows.",
    "login.badge": "Secure Access",
    "login.title": "Login to your workspace",
    "login.description": "Sign in with your hospital account to reach the dashboard for your role.",
    "login.email": "Email",
    "login.emailPlaceholder": "admin@hospital.com",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.emailRequired": "Email is required",
    "login.passwordRequired": "Password is required",
    "login.submit": "Sign in",
    "login.submitting": "Signing in...",
    "login.needAccount": "Need an account?",
    "login.registerLink": "Register here",
    "register.badge": "New Account",
    "register.title": "Create your hospital workspace login",
    "register.name": "Full name",
    "register.nameRequired": "Name is required",
    "register.email": "Email",
    "register.emailRequired": "Email is required",
    "register.password": "Password",
    "register.passwordRequired": "Password is required",
    "register.role": "Role",
    "register.submit": "Create account",
    "register.submitting": "Creating...",
    "register.hasAccount": "Already registered?",
    "register.loginLink": "Sign in",
    "dashboard.adminLabel": "Admin Dashboard",
    "dashboard.adminTitle": "Hospital operations overview",
    "dashboard.adminDescription": "Track admissions, staffing, revenue, and scheduling health from a single command center.",
    "dashboard.doctorLabel": "Doctor Dashboard",
    "dashboard.doctorTitle": "Your daily patient schedule",
    "dashboard.patientLabel": "Patient Dashboard",
    "dashboard.patientTitle": "Care journey at a glance",
    "dashboard.staffLabel": "Receptionist Dashboard",
    "dashboard.staffTitle": "Reception and operations overview",
    "dashboard.staffDescription": "Track check-ins, booking flow, and operational tasks assigned to support teams.",
    "stats.patients": "Patients",
    "stats.doctors": "Doctors",
    "stats.appointments": "Appointments",
    "stats.revenue": "Revenue",
    "stats.upcomingAppointments": "Upcoming appointments",
    "stats.totalAppointments": "Total appointments",
    "stats.outstandingBills": "Outstanding bills",
    "stats.paidBills": "Paid bills",
    "stats.scheduled": "Scheduled",
    "stats.completed": "Completed",
    "stats.pendingBilling": "Pending billing",
    "stats.liveCount": "Live count",
    "stats.liveTotal": "Live total",
    "stats.registeredPatients": "Registered patients",
    "stats.activeMedicalStaff": "Active medical staff",
    "stats.totalBookings": "Total bookings",
    "stats.totalBilledRevenue": "Total billed revenue",
    "admin.prioritiesTitle": "Today's priorities",
    "admin.prioritiesSubtitle": "Focus items for the front desk and care teams",
    "admin.priorityOne": "41 appointments scheduled, 6 need confirmation, and 3 overlap risks were prevented.",
    "admin.priorityTwo": "Billing follow-up required for 18 pending invoices due within 48 hours.",
    "admin.priorityThree": "Two departments are approaching staff capacity for evening shifts.",
    "admin.systemStatusTitle": "System status",
    "admin.systemStatusSubtitle": "Starter metrics can later be replaced with live charts",
    "admin.authentication": "Authentication",
    "admin.appointmentApi": "Appointment API",
    "admin.billingPipeline": "Billing pipeline",
    "system.healthy": "Healthy",
    "system.ready": "Ready",
    "system.scaffolded": "Scaffolded",
    "doctor.feedTitle": "Appointment feed",
    "doctor.feedSubtitle": "Latest live appointment records",
    "patient.latestAppointmentTitle": "Latest appointment",
    "patient.latestAppointmentSubtitle": "Pulled from live appointment data",
    "staff.receptionQueueTitle": "Reception queue",
    "staff.receptionQueueSubtitle": "Current activity snapshot",
    "staff.shiftPrioritiesTitle": "Shift priorities",
    "staff.shiftPrioritiesSubtitle": "Operational reminders",
    "staff.recordsAvailable": "{count} patient records are currently available.",
    "staff.coordinationNeeded": "{count} scheduled appointments need coordination.",
    "staff.contactReminder": "Update patient contact details before afternoon check-in cycle.",
    "staff.paymentFollowUp": "{count} billing records still need payment follow-up.",
    "common.loading": "Loading...",
    "common.noAppointments": "No appointments available yet.",
    "common.at": "at",
    "crud.management": "{resource} Management",
    "crud.editTitle": "Edit {resource}",
    "crud.addTitle": "Add {resource}",
    "crud.editSubtitle": "Update the selected record.",
    "crud.addSubtitle": "Create a new record in the system.",
    "crud.actions": "Actions",
    "crud.edit": "Edit",
    "crud.delete": "Delete",
    "crud.confirmDelete": "Delete this {resource} record?",
    "crud.saving": "Saving...",
    "crud.updateRecord": "Update record",
    "crud.createRecord": "Create record",
    "crud.cancel": "Cancel",
    "crud.directory": "{resource} directory",
    "crud.recordsCount": "{count} records",
    "table.noRecords": "No records yet.",
    "resource.patient": "Patient",
    "resource.doctor": "Doctor",
    "resource.appointment": "Appointment",
    "resource.billing": "Billing",
    "resource.department": "Department",
    "resource.staff": "Receptionist",
    "patients.title": "Patient records",
    "patients.subtitle": "Create, update, view, and delete patient profiles from the live backend.",
    "patients.description": "Real-time patient data from MongoDB.",
    "patients.firstName": "First name",
    "patients.lastName": "Last name",
    "patients.email": "Email",
    "patients.phone": "Phone",
    "patients.gender": "Gender",
    "patients.bloodType": "Blood type",
    "patients.city": "City",
    "patients.status": "Status",
    "patients.firstNameRequired": "First name is required",
    "patients.lastNameRequired": "Last name is required",
    "doctors.title": "Doctor profiles",
    "doctors.subtitle": "Manage doctors, specialties, department assignments, and consultation fees.",
    "doctors.description": "Live doctor data with create, update, and delete actions.",
    "doctors.selectDepartment": "Select department",
    "doctors.specialization": "Specialization",
    "doctors.licenseNumber": "License number",
    "doctors.yearsExperience": "Years of experience",
    "doctors.consultationFee": "Consultation fee",
    "doctors.specializationRequired": "Specialization is required",
    "doctors.licenseNumberRequired": "License number is required",
    "appointments.title": "Appointments",
    "appointments.subtitle": "Book, edit, review, and cancel appointments against live patient and doctor records.",
    "appointments.description": "Real-time appointment scheduling data.",
    "appointments.selectPatient": "Select patient",
    "appointments.selectDoctor": "Select doctor",
    "appointments.patientRequired": "Patient is required",
    "appointments.doctorRequired": "Doctor is required",
    "appointments.date": "Appointment date",
    "appointments.dateRequired": "Appointment date is required",
    "appointments.time": "Appointment time",
    "appointments.timeRequired": "Appointment time is required",
    "appointments.duration": "Duration (minutes)",
    "appointments.reason": "Reason for visit",
    "billing.title": "Billing and invoices",
    "billing.subtitle": "Track live billing records, payments, and invoice totals from the backend.",
    "billing.description": "Real-time financial records for appointments and services.",
    "billing.selectPatient": "Select patient",
    "billing.selectDoctor": "Select doctor",
    "billing.selectAppointment": "Select appointment",
    "billing.serviceDescription": "Service description",
    "billing.amount": "Amount",
    "billing.tax": "Tax",
    "billing.discount": "Discount",
    "billing.totalAmount": "Total amount",
    "billing.paymentStatus": "Payment status",
    "billing.paymentMethod": "Payment method",
    "billing.invoiceNumber": "Invoice number",
    "billing.serviceDescriptionRequired": "Service description is required",
    "billing.amountRequired": "Amount is required",
    "billing.totalAmountRequired": "Total amount is required",
    "departments.title": "Departments",
    "departments.subtitle": "Create, edit, view, and remove hospital departments using live backend data.",
    "departments.description": "Real-time department records from MongoDB.",
    "departments.name": "Department name",
    "departments.nameRequired": "Department name is required",
    "departments.descriptionField": "Description",
    "staff.title": "Reception management",
    "staff.subtitle": "Manage receptionist profiles, roles, and department assignments from the backend.",
    "staff.description": "Live receptionist directory with full CRUD actions.",
    "staff.role": "Role",
    "staff.roleRequired": "Role is required",
    "field.description": "Description",
    "field.department": "Department",
    "field.invoice": "Invoice",
    "field.service": "Service",
    "field.total": "Total",
    "field.date": "Date",
    "field.time": "Time",
    "field.specialty": "Specialty",
    "option.male": "Male",
    "option.female": "Female",
    "option.other": "Other",
    "option.active": "Active",
    "option.inactive": "Inactive",
    "option.scheduled": "Scheduled",
    "option.inProgress": "In-Progress",
    "option.completed": "Completed",
    "option.cancelled": "Cancelled",
    "option.rescheduled": "Rescheduled",
    "option.pending": "Pending",
    "option.paid": "Paid",
    "option.partiallyPaid": "Partially Paid",
    "error.failedToLoadDashboard": "Failed to load dashboard",
    "error.failedToLoad": "Failed to load {resource}",
    "success.created": "{resource} created",
    "success.updated": "{resource} updated",
    "success.deleted": "{resource} deleted",
    "error.create": "Failed to create {resource}",
    "error.update": "Failed to update {resource}",
    "error.delete": "Failed to delete {resource}",
    "unauthorized.title": "Unauthorized",
    "unauthorized.description": "You do not have permission to access this page.",
    "unauthorized.link": "Return to login",
    "notFound.title": "Page not found",
    "notFound.description": "The route you requested is not configured yet.",
    "notFound.link": "Go to dashboard",
  },
  hi: {
    "language.label": "भाषा",
    "language.english": "English",
    "language.hindi": "हिंदी",
    "brand.tagline": "केयर ऑपरेशंस और एडमिन कंट्रोल सेंटर",
    "brand.panel": "{role} पैनल",
    "brand.signedInAs": "इस रूप में लॉग इन",
    "brand.logout": "लॉग आउट",
    "brand.userFallback": "हॉस्पिटल एडमिन",
    "nav.dashboard": "डैशबोर्ड",
    "nav.patients": "मरीज",
    "nav.doctors": "डॉक्टर",
    "nav.appointments": "अपॉइंटमेंट",
    "nav.billing": "बिलिंग",
    "nav.departments": "विभाग",
    "nav.staff": "रिसेप्शनिस्ट",
    "role.admin": "एडमिन",
    "role.doctor": "डॉक्टर",
    "role.patient": "मरीज",
    "role.staff": "रिसेप्शनिस्ट",
    "auth.network": "सिटी केयर नेटवर्क",
    "auth.heroTitle": "हॉस्पिटल ऑपरेशंस, पेशेंट केयर और बिलिंग अब एक शांत और सुव्यवस्थित वर्कस्पेस में।",
    "auth.heroDescription": "एडमिनिस्ट्रेटर, क्लिनिशियन, स्टाफ और मरीजों के लिए रोल-आधारित एक्सेस और कनेक्टेड रिकॉर्ड्स के साथ तैयार किया गया है।",
    "auth.operations": "ऑपरेशंस",
    "auth.operationsDescription": "अपॉइंटमेंट, मरीज, विभाग और स्टाफिंग अब एक ही फ्लो में।",
    "auth.financials": "वित्तीय प्रबंधन",
    "auth.financialsDescription": "लाइव रिकॉर्ड्स और रोल-आधारित वर्कफ़्लो के साथ बिलिंग की पूरी विज़िबिलिटी।",
    "login.badge": "सिक्योर एक्सेस",
    "login.title": "अपने वर्कस्पेस में लॉगिन करें",
    "login.description": "अपने अस्पताल अकाउंट से साइन इन करें और अपने रोल के डैशबोर्ड तक पहुंचें।",
    "login.email": "ईमेल",
    "login.emailPlaceholder": "admin@hospital.com",
    "login.password": "पासवर्ड",
    "login.passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "login.emailRequired": "ईमेल आवश्यक है",
    "login.passwordRequired": "पासवर्ड आवश्यक है",
    "login.submit": "साइन इन",
    "login.submitting": "साइन इन हो रहा है...",
    "login.needAccount": "अकाउंट चाहिए?",
    "login.registerLink": "यहां रजिस्टर करें",
    "register.badge": "नया अकाउंट",
    "register.title": "अपने अस्पताल वर्कस्पेस का लॉगिन बनाएं",
    "register.name": "पूरा नाम",
    "register.nameRequired": "नाम आवश्यक है",
    "register.email": "ईमेल",
    "register.emailRequired": "ईमेल आवश्यक है",
    "register.password": "पासवर्ड",
    "register.passwordRequired": "पासवर्ड आवश्यक है",
    "register.role": "भूमिका",
    "register.submit": "अकाउंट बनाएं",
    "register.submitting": "बनाया जा रहा है...",
    "register.hasAccount": "पहले से रजिस्टर हैं?",
    "register.loginLink": "साइन इन",
    "dashboard.adminLabel": "एडमिन डैशबोर्ड",
    "dashboard.adminTitle": "हॉस्पिटल ऑपरेशंस ओवरव्यू",
    "dashboard.adminDescription": "एक ही कंट्रोल सेंटर से एडमिशन, स्टाफिंग, राजस्व और शेड्यूलिंग की स्थिति ट्रैक करें।",
    "dashboard.doctorLabel": "डॉक्टर डैशबोर्ड",
    "dashboard.doctorTitle": "आज का आपका पेशेंट शेड्यूल",
    "dashboard.patientLabel": "पेशेंट डैशबोर्ड",
    "dashboard.patientTitle": "आपकी केयर जर्नी एक नजर में",
    "dashboard.staffLabel": "रिसेप्शनिस्ट डैशबोर्ड",
    "dashboard.staffTitle": "फ्रंट डेस्क और ऑपरेशंस ओवरव्यू",
    "dashboard.staffDescription": "चेक-इन, बुकिंग फ्लो और सपोर्ट टीमों के कार्यों पर नज़र रखें।",
    "stats.patients": "मरीज",
    "stats.doctors": "डॉक्टर",
    "stats.appointments": "अपॉइंटमेंट",
    "stats.revenue": "राजस्व",
    "stats.upcomingAppointments": "आगामी अपॉइंटमेंट",
    "stats.totalAppointments": "कुल अपॉइंटमेंट",
    "stats.outstandingBills": "बकाया बिल",
    "stats.paidBills": "भुगतान किए गए बिल",
    "stats.scheduled": "निर्धारित",
    "stats.completed": "पूर्ण",
    "stats.pendingBilling": "लंबित बिलिंग",
    "stats.liveCount": "लाइव काउंट",
    "stats.liveTotal": "लाइव टोटल",
    "stats.registeredPatients": "रजिस्टर्ड मरीज",
    "stats.activeMedicalStaff": "सक्रिय मेडिकल स्टाफ",
    "stats.totalBookings": "कुल बुकिंग",
    "stats.totalBilledRevenue": "कुल बिल किया गया राजस्व",
    "admin.prioritiesTitle": "आज की प्राथमिकताएं",
    "admin.prioritiesSubtitle": "फ्रंट डेस्क और केयर टीमों के लिए फोकस क्षेत्र",
    "admin.priorityOne": "41 अपॉइंटमेंट निर्धारित हैं, 6 को पुष्टि चाहिए और 3 ओवरलैप जोखिम रोके गए हैं।",
    "admin.priorityTwo": "अगले 48 घंटों में देय 18 लंबित इनवॉइस के लिए बिलिंग फॉलो-अप जरूरी है।",
    "admin.priorityThree": "दो विभाग शाम की शिफ्ट के लिए स्टाफ क्षमता की सीमा के करीब हैं।",
    "admin.systemStatusTitle": "सिस्टम स्टेटस",
    "admin.systemStatusSubtitle": "इन शुरुआती मेट्रिक्स को बाद में लाइव चार्ट्स से बदला जा सकता है",
    "admin.authentication": "ऑथेंटिकेशन",
    "admin.appointmentApi": "अपॉइंटमेंट API",
    "admin.billingPipeline": "बिलिंग पाइपलाइन",
    "system.healthy": "सामान्य",
    "system.ready": "तैयार",
    "system.scaffolded": "स्कैफोल्डेड",
    "doctor.feedTitle": "अपॉइंटमेंट फ़ीड",
    "doctor.feedSubtitle": "सबसे नए लाइव अपॉइंटमेंट रिकॉर्ड्स",
    "patient.latestAppointmentTitle": "नवीनतम अपॉइंटमेंट",
    "patient.latestAppointmentSubtitle": "लाइव अपॉइंटमेंट डेटा से लिया गया",
    "staff.receptionQueueTitle": "रिसेप्शन क्यू",
    "staff.receptionQueueSubtitle": "वर्तमान गतिविधि का स्नैपशॉट",
    "staff.shiftPrioritiesTitle": "शिफ्ट प्राथमिकताएं",
    "staff.shiftPrioritiesSubtitle": "ऑपरेशनल रिमाइंडर",
    "staff.recordsAvailable": "अभी {count} मरीज रिकॉर्ड उपलब्ध हैं।",
    "staff.coordinationNeeded": "{count} निर्धारित अपॉइंटमेंट के लिए समन्वय चाहिए।",
    "staff.contactReminder": "दोपहर की चेक-इन साइकिल से पहले मरीजों की संपर्क जानकारी अपडेट करें।",
    "staff.paymentFollowUp": "{count} बिलिंग रिकॉर्ड्स पर अभी भुगतान फॉलो-अप बाकी है।",
    "common.loading": "लोड हो रहा है...",
    "common.noAppointments": "अभी कोई अपॉइंटमेंट उपलब्ध नहीं है।",
    "common.at": "पर",
    "crud.management": "{resource} प्रबंधन",
    "crud.editTitle": "{resource} संपादित करें",
    "crud.addTitle": "{resource} जोड़ें",
    "crud.editSubtitle": "चयनित रिकॉर्ड अपडेट करें।",
    "crud.addSubtitle": "सिस्टम में नया रिकॉर्ड बनाएं।",
    "crud.actions": "कार्य",
    "crud.edit": "संपादित करें",
    "crud.delete": "हटाएं",
    "crud.confirmDelete": "क्या आप यह {resource} रिकॉर्ड हटाना चाहते हैं?",
    "crud.saving": "सेव हो रहा है...",
    "crud.updateRecord": "रिकॉर्ड अपडेट करें",
    "crud.createRecord": "रिकॉर्ड बनाएं",
    "crud.cancel": "रद्द करें",
    "crud.directory": "{resource} निर्देशिका",
    "crud.recordsCount": "{count} रिकॉर्ड",
    "table.noRecords": "अभी कोई रिकॉर्ड नहीं है।",
    "resource.patient": "मरीज",
    "resource.doctor": "डॉक्टर",
    "resource.appointment": "अपॉइंटमेंट",
    "resource.billing": "बिलिंग",
    "resource.department": "विभाग",
    "resource.staff": "रिसेप्शनिस्ट",
    "patients.title": "मरीज रिकॉर्ड",
    "patients.subtitle": "लाइव बैकएंड से मरीज प्रोफाइल बनाएं, अपडेट करें, देखें और हटाएं।",
    "patients.description": "MongoDB से रियल-टाइम मरीज डेटा।",
    "patients.firstName": "पहला नाम",
    "patients.lastName": "अंतिम नाम",
    "patients.email": "ईमेल",
    "patients.phone": "फोन",
    "patients.gender": "लिंग",
    "patients.bloodType": "ब्लड टाइप",
    "patients.city": "शहर",
    "patients.status": "स्टेटस",
    "patients.firstNameRequired": "पहला नाम आवश्यक है",
    "patients.lastNameRequired": "अंतिम नाम आवश्यक है",
    "doctors.title": "डॉक्टर प्रोफाइल",
    "doctors.subtitle": "डॉक्टर, विशेषज्ञता, विभाग और कंसल्टेशन फीस प्रबंधित करें।",
    "doctors.description": "लाइव डॉक्टर डेटा, क्रिएट, अपडेट और डिलीट एक्शन के साथ।",
    "doctors.selectDepartment": "विभाग चुनें",
    "doctors.specialization": "विशेषज्ञता",
    "doctors.licenseNumber": "लाइसेंस नंबर",
    "doctors.yearsExperience": "अनुभव के वर्ष",
    "doctors.consultationFee": "कंसल्टेशन फीस",
    "doctors.specializationRequired": "विशेषज्ञता आवश्यक है",
    "doctors.licenseNumberRequired": "लाइसेंस नंबर आवश्यक है",
    "appointments.title": "अपॉइंटमेंट",
    "appointments.subtitle": "लाइव मरीज और डॉक्टर रिकॉर्ड्स के साथ अपॉइंटमेंट बुक, संपादित, देखें और रद्द करें।",
    "appointments.description": "रियल-टाइम अपॉइंटमेंट शेड्यूलिंग डेटा।",
    "appointments.selectPatient": "मरीज चुनें",
    "appointments.selectDoctor": "डॉक्टर चुनें",
    "appointments.patientRequired": "मरीज आवश्यक है",
    "appointments.doctorRequired": "डॉक्टर आवश्यक है",
    "appointments.date": "अपॉइंटमेंट तिथि",
    "appointments.dateRequired": "अपॉइंटमेंट तिथि आवश्यक है",
    "appointments.time": "अपॉइंटमेंट समय",
    "appointments.timeRequired": "अपॉइंटमेंट समय आवश्यक है",
    "appointments.duration": "अवधि (मिनट)",
    "appointments.reason": "विज़िट का कारण",
    "billing.title": "बिलिंग और इनवॉइस",
    "billing.subtitle": "बैकएंड से लाइव बिलिंग रिकॉर्ड, भुगतान और इनवॉइस टोटल ट्रैक करें।",
    "billing.description": "अपॉइंटमेंट और सेवाओं के लिए रियल-टाइम वित्तीय रिकॉर्ड।",
    "billing.selectPatient": "मरीज चुनें",
    "billing.selectDoctor": "डॉक्टर चुनें",
    "billing.selectAppointment": "अपॉइंटमेंट चुनें",
    "billing.serviceDescription": "सेवा विवरण",
    "billing.amount": "राशि",
    "billing.tax": "कर",
    "billing.discount": "छूट",
    "billing.totalAmount": "कुल राशि",
    "billing.paymentStatus": "भुगतान स्थिति",
    "billing.paymentMethod": "भुगतान तरीका",
    "billing.invoiceNumber": "इनवॉइस नंबर",
    "billing.serviceDescriptionRequired": "सेवा विवरण आवश्यक है",
    "billing.amountRequired": "राशि आवश्यक है",
    "billing.totalAmountRequired": "कुल राशि आवश्यक है",
    "departments.title": "विभाग",
    "departments.subtitle": "लाइव बैकएंड डेटा से अस्पताल के विभाग बनाएं, संपादित करें, देखें और हटाएं।",
    "departments.description": "MongoDB से रियल-टाइम विभाग रिकॉर्ड।",
    "departments.name": "विभाग का नाम",
    "departments.nameRequired": "विभाग का नाम आवश्यक है",
    "departments.descriptionField": "विवरण",
    "staff.title": "रिसेप्शन प्रबंधन",
    "staff.subtitle": "बैकएंड से रिसेप्शनिस्ट प्रोफाइल, भूमिकाएं और विभाग असाइनमेंट प्रबंधित करें।",
    "staff.description": "पूर्ण CRUD एक्शन के साथ लाइव रिसेप्शनिस्ट डायरेक्टरी।",
    "staff.role": "भूमिका",
    "staff.roleRequired": "भूमिका आवश्यक है",
    "field.description": "विवरण",
    "field.department": "विभाग",
    "field.invoice": "इनवॉइस",
    "field.service": "सेवा",
    "field.total": "कुल",
    "field.date": "तिथि",
    "field.time": "समय",
    "field.specialty": "विशेषज्ञता",
    "option.male": "पुरुष",
    "option.female": "महिला",
    "option.other": "अन्य",
    "option.active": "सक्रिय",
    "option.inactive": "निष्क्रिय",
    "option.scheduled": "निर्धारित",
    "option.inProgress": "प्रगति में",
    "option.completed": "पूर्ण",
    "option.cancelled": "रद्द",
    "option.rescheduled": "पुनर्निर्धारित",
    "option.pending": "लंबित",
    "option.paid": "भुगतान हो चुका",
    "option.partiallyPaid": "आंशिक भुगतान",
    "error.failedToLoadDashboard": "डैशबोर्ड लोड नहीं हो सका",
    "error.failedToLoad": "{resource} लोड नहीं हो सका",
    "success.created": "{resource} बनाया गया",
    "success.updated": "{resource} अपडेट किया गया",
    "success.deleted": "{resource} हटाया गया",
    "error.create": "{resource} बनाया नहीं जा सका",
    "error.update": "{resource} अपडेट नहीं हो सका",
    "error.delete": "{resource} हटाया नहीं जा सका",
    "unauthorized.title": "अनधिकृत",
    "unauthorized.description": "आपको इस पेज तक पहुंचने की अनुमति नहीं है।",
    "unauthorized.link": "लॉगिन पर लौटें",
    "notFound.title": "पेज नहीं मिला",
    "notFound.description": "आपके द्वारा मांगा गया रूट अभी कॉन्फ़िगर नहीं किया गया है।",
    "notFound.link": "डैशबोर्ड पर जाएं",
  },
};

const LanguageContext = createContext(null);

function interpolate(template, values) {
  return Object.entries(values || {}).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template
  );
}

function repairMojibake(value) {
  if (typeof value !== "string" || !textDecoder || !/(?:à¤|à¥)/.test(value)) {
    return value;
  }

  try {
    const bytes = Uint8Array.from(value, (character) => character.charCodeAt(0) & 0xff);
    const decoded = textDecoder.decode(bytes);
    return /[\u0900-\u097F]/.test(decoded) ? decoded : value;
  } catch (_error) {
    return value;
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") {
      return "en";
    }

    return window.localStorage.getItem(STORAGE_KEY) || "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "hi" ? "hi" : "en";
  }, [language]);

  const value = useMemo(() => {
    const locale = language === "hi" ? "hi-IN" : "en-IN";
    const dictionary = translations[language] || translations.en;

    const normalizeText = (text) => (language === "hi" ? repairMojibake(text) : text);
    const t = (key, values) => normalizeText(interpolate(dictionary[key] || translations.en[key] || key, values));
    const formatDate = (value) => new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(value));
    const formatCurrency = (value) =>
      new Intl.NumberFormat(locale, {
        style: "currency",
        currency: "INR",
        maximumFractionDigits: 2,
      }).format(Number(value || 0));

    return {
      language,
      setLanguage,
      t,
      formatDate,
      formatCurrency,
      normalizeText,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
